---
title: "Testing tmap R package"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Brasil estados por população


```{r}
library(tidyverse)
library(here) # helps accessing files relative to a project root to stop the working directory insanity
library(sidrar)
library(tmap)
library(brmap)
```

```{r data_import}
# Baixa do site do IBGE ou carrega os dados salvos localmente
if (file.exists(here("data", "populacao.csv")) == FALSE) {
  # importa o número de habitantes de cada estado (IBGE)
  populacao <-
    get_sidra(6579,
              period = "all",
              geo = "State",
              format = 3) %>% as_tibble()
  
  dir.create("data")
  write.csv(populacao, here("data", "populacao.csv"), fileEncoding = "UTF-8")
} else populacao <- read.csv(here("data", "populacao.csv"))
  


# Transforma as variáveis para compatibilizar com o brmap
map_data <- populacao %>%
  mutate(
    estado_cod = as.numeric(`Unidade da Federação (Código)`),
    ano = as.numeric(Ano)
    ) %>%
  right_join(brmap::brmap_estado_simples, by = "estado_cod")

map_data <- st_as_sf(map_data)
```


```{r base_map}
base_map <- map_data %>%
  filter(ano == 2019) %>%
  tm_shape(name = "Brasil, 2019")
```

```{r simple_map}
base_map +
  tm_polygons("Valor", title = "População",
              legend.format = list(big.num.abbr = c("mi" = 6, "bi" = 9)))
```


```{r bubbles}
base_map +
  tm_polygons("white") +
  tm_bubbles("Valor", title.size = "População",
             legend.format = list(big.num.abbr = c("mi" = 6, "bi" = 9)))
```

